### ISSUE TITLE
Desktop notification not working

### ISSUE THREAD

**Issue by ejaazkhan** [linear/linear#205] opened 2022-06-17 08:15 UTC
![image](https://user-images.githubusercontent.com/67804911/174256789-160c8da7-ede7-4621-bc3b-cdadb6a7c2e3.png)

https://user-images.githubusercontent.com/67804911/174257191-1119a53b-6a59-4cc7-9d7e-8d17b1380609.mp4

**Comment by pacocoursey** [comment] 2022-08-15 14:43
Confirmed this is a valid bug. Closing because this is the not the right place for it – please join our community slack to surface product bugs in the future and we'll get back to you _much_ quicker :)

https://linear.app/docs/tutorials#slack-community

**Closed by pacocoursey** 2022-08-15 14:43 UTC
Labels: product
